! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE GMASSDIAG(YDGEOMETRY,YDGMV,YDML_CHEM,YGFL,YDDYN,PGMV,PGMVS,PGMVT1S,PGFL,PGFLT1,KOPT,LDTROP)
!
!     Purpose.   Global mass diagnostics for atmosphere and GFL tracers
!     --------   
!
!*   Interface.
!    ----------
!
!        *CALL* *GMASSDIAG (PGMVS,PGMVT1S, PGFLT, PGFLT1)
!
!     Explicit arguments :
!     --------------------
!
!!     INPUT:
!     -------------
!        PGMVS       : surface GMV variables at t and t-dt.
!        PGMVS       : surface GMV variables at t +dt 
!        PGFL        : GFL variables buffer t0 t1
!        PGFLT1      : GFL variables buffer t + dt
!
!        Implicit arguments :  None.
!        --------------------
!
!     Method.
!     -------

!     Externals.   See includes below.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!        Michail Diamantakis   *ECMWF* 
!
! Modifications
! -------------
!! J. Flemming: June 2016, tropospheric budget option  
!    F. Vana (Jan 2023) Better GMV & GFL pointers

USE GEOMETRY_MOD   , ONLY : GEOMETRY
USE YOMGMV         , ONLY : TGMV
USE MODEL_CHEM_MOD , ONLY : MODEL_CHEM_TYPE
USE YOM_YGFL       , ONLY : TYPE_GFLD
USE PARKIND1       , ONLY : JPIM     ,JPRB, JPRD
USE YOMHOOK        , ONLY : LHOOK    ,DR_HOOK, JPHOOK
USE YOMDYN         , ONLY : TDYN
USE YOMCST         , ONLY : RA, RPI, RG
USE YOMCT3         , ONLY : NSTEP
USE YOMMP0         , ONLY : MYPROC, NPROC
USE YOMLUN         , ONLY : NULOUT
IMPLICIT NONE

! arguments
TYPE(GEOMETRY)       ,INTENT(IN)    :: YDGEOMETRY
TYPE(TGMV)           ,INTENT(IN)    :: YDGMV
TYPE(TDYN)           ,INTENT(INOUT) :: YDDYN
TYPE(MODEL_CHEM_TYPE),INTENT(INOUT) :: YDML_CHEM
TYPE(TYPE_GFLD)      ,INTENT(INOUT) :: YGFL
REAL(KIND=JPRB)      ,INTENT(IN)    :: PGMV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%NDIMGMV,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)      ,INTENT(IN)    :: PGMVS(YDGEOMETRY%YRDIM%NPROMA,YDGMV%NDIMGMVS,YDGEOMETRY%YRDIM%NGPBLKS) 
REAL(KIND=JPRB)      ,INTENT(IN)    :: PGMVT1S(YDGEOMETRY%YRDIM%NPROMA,YDGMV%YT1%NDIMS,YDGEOMETRY%YRDIM%NGPBLKS) 
REAL(KIND=JPRB)      ,INTENT(IN)    :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIM, &
 &                                     YDGEOMETRY%YRDIM%NGPBLKS) 
REAL(KIND=JPRB)      ,INTENT(IN)    :: PGFLT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIM1, &
 &                                     YDGEOMETRY%YRDIM%NGPBLKS)
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KOPT  
LOGICAL ,INTENT(IN), OPTIONAL    :: LDTROP

! Local variables
INTEGER(KIND=JPIM) :: JKGLO, IST, IEND, IBL, JROF, JLEV, JGFL, JJ, IGFLADV, IOPT, IQ
INTEGER(KIND=JPIM) :: IGFLIND(YGFL%NUMFLDS)
REAL(KIND=JPRB) :: ZPRE0(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG),&
 &  ZPRE1(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZPRESF(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB) :: ZWORK1(YDGEOMETRY%YRDIM%NPROMA,2,YDGEOMETRY%YRDIM%NGPBLKS),&
 &  ZWORK3(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZWORK2T0(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG),&
 &  ZWORK2T1(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZWORK3T0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG),&
 &    ZWORK3T1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZPRES0(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIM%NGPBLKS),&
 &  ZPRES1(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) :: ZPTROP(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIM%NGPBLKS)
INTEGER(KIND=JPIM) :: ITROPL(YDGEOMETRY%YRDIM%NPROMA)

REAL(KIND=JPRB) :: ZPNORMS(3,2)
REAL(KIND=JPRD) :: ZAREA, ZPNORMS_DP(3,2)

REAL(KIND=JPRB), ALLOCATABLE :: ZGFLNORMS(:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZGFLNORMS_DP(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZWORK5(:,:,:)

REAL(KIND=JPRB) :: ZMASSADJ=1.0043_JPRB 
                           ! adjustment factor when computing total mass
                           ! to conmpensate perfect sphere assumption.
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
CHARACTER(LEN=11)  :: CLDOMAIN, CLT
LOGICAL            :: LLTROP

#include "gpnorm1.intfb.h"
#include "gppwc.intfb.h"
#include "gppwcvfe.intfb.h"
#include "gphpre.intfb.h"
#include "troplev.intfb.h"

IF (LHOOK) CALL DR_HOOK('GMASSDIAG',0,ZHOOK_HANDLE)

! call before (1) or after mass fixer(0 or not present) 
IF ( PRESENT(KOPT)) THEN 
  IOPT=KOPT
ELSE
  IOPT=0
ENDIF

IF ( PRESENT(LDTROP)) THEN 
  LLTROP=LDTROP  
ELSE
  LLTROP=.FALSE.  
ENDIF

CLT=' after MF  '
IF (IOPT == 1 ) CLT= ' before MF ' 
CLDOMAIN='ATMOSPHERE ' 
IF (LLTROP) CLDOMAIN='TROPOSPHERE '

DO JGFL=1,YGFL%NUMFLDS
  IF( YGFL%YCOMP(JGFL)%IGRBCODE  ==  133  ) IQ = JGFL
ENDDO

!---------------------------------------------------------
! Calculate pressure
!---------------------------------------------------------
IST=1
!$OMP PARALLEL DO SCHEDULE(STATIC) &
!$OMP& PRIVATE(JKGLO,IEND,IBL,JROF,JLEV) &
!$OMP& PRIVATE(ZPRE0,ZPRE1,ITROPL,ZPRESF)
DO JKGLO=1,YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIM%NPROMA
  IEND=MIN(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRGEM%NGPTOT-JKGLO+1)
  IBL=(JKGLO-1)/YDGEOMETRY%YRDIM%NPROMA+1
  DO JROF=IST,IEND
    ZPRE0(JROF,YDGEOMETRY%YRDIMV%NFLEVG) = EXP(PGMVS(JROF,YDGMV%YPH9%MSP,IBL))
    ZPRE1(JROF,YDGEOMETRY%YRDIMV%NFLEVG) = EXP(PGMVT1S(JROF,YDGMV%YT1%MSP,IBL))
  ENDDO
  CALL GPHPRE(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,IST,IEND,&
   & YDGEOMETRY%YRVAB,YDGEOMETRY%YRCVER,ZPRE0,PRESF=ZPRESF ) 
  CALL GPHPRE(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,IST,IEND, &
   & YDGEOMETRY%YRVAB,YDGEOMETRY%YRCVER,ZPRE1)

! pressure of top level for tracer budget  
  DO JROF=IST,IEND
     ZPTROP(JROF,IBL)=0.0_JPRB 
  ENDDO
! set to tropopause pressure 
  IF (LLTROP) THEN  
    IF (YDML_CHEM%YRCOMPO%LCHEM_TROPO ) THEN
      CALL TROPLEV(YDGEOMETRY%YRDIM%NPROMA, IST, IEND, YDGEOMETRY%YRDIMV%NFLEVG ,.FALSE.,&
         & PGMV(:,:,YDGMV%YPH9%MT,IBL), PGFLT1(:,:,YGFL%YCOMP(IQ)%MP,IBL), ZPRESF,ITROPL)
      DO JROF=IST,IEND
         ZPTROP(JROF,IBL)=ZPRESF(JROF,ITROPL(JROF))
      ENDDO 
    ELSE 
      ! use static pressure tropopause  
      DO JROF=IST,IEND
        ZPTROP(JROF,IBL) = 24000_JPRB - 14800_JPRB * (COS(YDGEOMETRY%YRGSGEOM_NB%GELAT(JKGLO+JROF-1)))**4_JPIM
      ENDDO
    ENDIF 
  ENDIF 

  DO JLEV=0,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=IST,IEND
      ZPRES0(JROF,JLEV,IBL) = ZPRE0(JROF,JLEV)
      ZPRES1(JROF,JLEV,IBL) = ZPRE1(JROF,JLEV)
    ENDDO
  ENDDO
ENDDO
!$OMP END PARALLEL DO


IST=1
!$OMP PARALLEL DO SCHEDULE(STATIC) &
!$OMP& PRIVATE(JKGLO,IEND,IBL) &
!$OMP& PRIVATE(ZPRE0,ZPRE1,ZWORK3,ZWORK2T0,ZWORK2T1)
DO JKGLO=1,YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIM%NPROMA
  IEND=MIN(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRGEM%NGPTOT-JKGLO+1)
  IBL=(JKGLO-1)/YDGEOMETRY%YRDIM%NPROMA+1
  ZPRE0(IST:IEND,0:YDGEOMETRY%YRDIMV%NFLEVG)=ZPRES0(IST:IEND,0:YDGEOMETRY%YRDIMV%NFLEVG,IBL)
  ZPRE1(IST:IEND,0:YDGEOMETRY%YRDIMV%NFLEVG)=ZPRES1(IST:IEND,0:YDGEOMETRY%YRDIMV%NFLEVG,IBL)
  ZWORK3(IST:IEND,1:YDGEOMETRY%YRDIMV%NFLEVG)=1.0_JPRB
  IF (YGFL%NOPTVFE==1) THEN
    CALL GPPWCVFE(YDGEOMETRY,YDGEOMETRY%YRDIM%NPROMA,IST,IEND,YDGEOMETRY%YRDIMV%NFLEVG,ZWORK2T0,ZWORK3,ZPRE0)
    CALL GPPWCVFE(YDGEOMETRY,YDGEOMETRY%YRDIM%NPROMA,IST,IEND,YDGEOMETRY%YRDIMV%NFLEVG,ZWORK2T1,ZWORK3,ZPRE1)
  ELSE
    CALL GPPWC(YDGEOMETRY%YRDIM%NPROMA,IST,IEND,YDGEOMETRY%YRDIMV%NFLEVG,ZWORK2T0,ZWORK3,ZPRE0)
    CALL GPPWC(YDGEOMETRY%YRDIM%NPROMA,IST,IEND,YDGEOMETRY%YRDIMV%NFLEVG,ZWORK2T1,ZWORK3,ZPRE1)
  ENDIF
  ZWORK1(IST:IEND,1,IBL)=ZWORK2T0(IST:IEND,YDGEOMETRY%YRDIMV%NFLEVG)
  ZWORK1(IST:IEND,2,IBL)=ZWORK2T1(IST:IEND,YDGEOMETRY%YRDIMV%NFLEVG)
ENDDO
!$OMP END PARALLEL DO

CALL GPNORM1(YDGEOMETRY,ZWORK1,2,.FALSE.,PNORMS=ZPNORMS,PNORMS_DP=ZPNORMS_DP)

IF( NSTEP == 0 ) YDDYN%GPMASSI = ZPNORMS_DP(1,1)

ZAREA=4.0_JPRD*RPI*RA*RA*ZMASSADJ

IF (MYPROC == 1.OR.NPROC == 1) THEN
  WRITE(NULOUT,*)
  WRITE(NULOUT,*) '-----------  ' , CLDOMAIN, 'MASS BUDGETS before vs after SL ', CLT, ' -----------'
  WRITE(NULOUT,*) ' init MASS(kgr/m**2)     current MASS        total MASS(kgr)     mean PRESS(Pa)'
  WRITE(NULOUT,*) '-------------------------------------------------------------------------------'
  WRITE(NULOUT,'(2(F20.12,2X),E20.15,2X,F20.12)') YDDYN%GPMASSI,ZPNORMS_DP(1,1),ZAREA*ZPNORMS_DP(1,1),RG*ZPNORMS_DP(1,1)
  WRITE(NULOUT,'(22X,F20.12,2X,E20.15,2X,F20.12)') ZPNORMS_DP(1,2),ZAREA*ZPNORMS_DP(1,2),RG*ZPNORMS_DP(1,2)
  WRITE(NULOUT,*) '-------------------------------------------------------------------------------'
ENDIF

IGFLADV=0
IGFLIND=0
DO JGFL=1,YGFL%NUMFLDS
  IF ( ( YGFL%YCOMP(JGFL)%LADV .AND. YGFL%YCOMP(JGFL)%LGP ) .AND. &
 &     (TRIM(ADJUSTL(YGFL%YCOMP(JGFL)%CNAME)) /= 'CLOUD FRACTION' ) ) THEN
    IGFLADV=IGFLADV+1
    IGFLIND(IGFLADV)=JGFL
  ENDIF
ENDDO

IF (IGFLADV>0) THEN
  ALLOCATE(ZWORK5(YDGEOMETRY%YRDIM%NPROMA,2*IGFLADV,YDGEOMETRY%YRDIM%NGPBLKS))
  ALLOCATE(ZGFLNORMS(3,2*IGFLADV))
  ALLOCATE(ZGFLNORMS_DP(3,2*IGFLADV))
ENDIF

IST=1
DO JJ=1,IGFLADV
  JGFL=IGFLIND(JJ)
!$OMP PARALLEL DO SCHEDULE(STATIC) &
!$OMP& PRIVATE(JKGLO,IEND,IBL,JLEV,JROF) &
!$OMP& PRIVATE(ZPRE0,ZPRE1,ZWORK3T0,ZWORK3T1,ZWORK2T0,ZWORK2T1)
  DO JKGLO=1,YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIM%NPROMA
    IEND=MIN(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRGEM%NGPTOT-JKGLO+1)
    IBL=(JKGLO-1)/YDGEOMETRY%YRDIM%NPROMA+1
    ZPRE0(IST:IEND,0)=ZPRES0(IST:IEND,0,IBL)
    ZPRE1(IST:IEND,0)=ZPRES1(IST:IEND,0,IBL)
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=IST,IEND
        ZWORK3T0(JROF,JLEV)=PGFL(JROF,JLEV,YGFL%YCOMP(JGFL)%MP9_PH,IBL)
        ZWORK3T1(JROF,JLEV)=PGFLT1(JROF,JLEV,YGFL%YCOMP(JGFL)%MP1,IBL)
        ZPRE0(JROF,JLEV) = ZPRES0(JROF,JLEV,IBL) 
        ZPRE1(JROF,JLEV) = ZPRES1(JROF,JLEV,IBL)
        IF (ZPTROP(JROF,IBL) >= ZPRE0(JROF,JLEV)) ZWORK3T0(JROF,JLEV)=0.0_JPRB 
        IF (ZPTROP(JROF,IBL) >= ZPRE1(JROF,JLEV)) ZWORK3T1(JROF,JLEV)=0.0_JPRB 
      ENDDO
    ENDDO
    IF (YGFL%NOPTVFE==1) THEN
      CALL GPPWCVFE(YDGEOMETRY,YDGEOMETRY%YRDIM%NPROMA,IST,IEND,YDGEOMETRY%YRDIMV%NFLEVG,ZWORK2T0,ZWORK3T0,ZPRE0)
      CALL GPPWCVFE(YDGEOMETRY,YDGEOMETRY%YRDIM%NPROMA,IST,IEND,YDGEOMETRY%YRDIMV%NFLEVG,ZWORK2T1,ZWORK3T1,ZPRE1)
    ELSE
      CALL GPPWC(YDGEOMETRY%YRDIM%NPROMA,IST,IEND,YDGEOMETRY%YRDIMV%NFLEVG,ZWORK2T0,ZWORK3T0,ZPRE0)
      CALL GPPWC(YDGEOMETRY%YRDIM%NPROMA,IST,IEND,YDGEOMETRY%YRDIMV%NFLEVG,ZWORK2T1,ZWORK3T1,ZPRE1)
    ENDIF
    DO JROF=IST,IEND
      ZWORK5(JROF,2*JJ-1,IBL)=ZWORK2T0(JROF,YDGEOMETRY%YRDIMV%NFLEVG)
      ZWORK5(JROF,2*JJ,IBL)=ZWORK2T1(JROF,YDGEOMETRY%YRDIMV%NFLEVG)
    ENDDO
  ENDDO
!$OMP END PARALLEL DO
ENDDO

IF (IGFLADV>0) THEN
  IF (NPROC==1.OR.MYPROC==1) THEN
  WRITE(NULOUT,*)
  WRITE(NULOUT,*) '------------  ' , CLDOMAIN, 'MASS BUDGETS before vs after SL ', CLT, '-----------'
  ENDIF
  CALL GPNORM1(YDGEOMETRY,ZWORK5,2*IGFLADV,.FALSE.,PNORMS=ZGFLNORMS,PNORMS_DP=ZGFLNORMS_DP)
  IF (NPROC==1.OR.MYPROC==1) THEN
    WRITE(NULOUT,*) '        tracer NAME     mean MASS(kgr/m**2)   total MASS(kgr)    mean PRESS(Pa)'
    WRITE(NULOUT,*) '-------------------------------------------------------------------------------'
    DO JJ=1,IGFLADV
      JGFL=IGFLIND(JJ)
      ! Use DP for accurate mass difference calculation
      IF (IOPT == 1 ) YDML_CHEM%YRCHEM%SMASSCOR(JGFL,3)=REAL(ZGFLNORMS_DP(1,2*JJ)-ZGFLNORMS_DP(1,2*JJ-1),KIND=JPRB)
      IF (IOPT == 0 ) YDML_CHEM%YRCHEM%SMASSCOR(JGFL,4)=REAL(ZGFLNORMS_DP(1,2*JJ)-ZGFLNORMS_DP(1,2*JJ-1),KIND=JPRB)
      WRITE(NULOUT,'(A20,2X,F20.12,2X,E20.15,2X,F20.12)') TRIM(ADJUSTL(YGFL%YCOMP(JGFL)%CNAME)), &
        & ZGFLNORMS_DP(1,2*JJ-1),ZAREA*ZGFLNORMS_DP(1,2*JJ-1),RG*ZGFLNORMS_DP(1,2*JJ-1)
      WRITE(NULOUT,'(22X,F20.12,2X,E20.15,2X,F20.12)') ZGFLNORMS_DP(1,2*JJ),&
        & ZAREA*ZGFLNORMS_DP(1,2*JJ),RG*ZGFLNORMS_DP(1,2*JJ)
    ENDDO
    WRITE(NULOUT,*) '-------------------------------------------------------------------------------'
    WRITE(NULOUT,*)
  ENDIF
  DEALLOCATE(ZWORK5)
  DEALLOCATE(ZGFLNORMS)
  DEALLOCATE(ZGFLNORMS_DP)
ENDIF

IF (YGFL%NMFDIAGLEV>1) THEN
!!!!!
!!!!! EXTRA computation for dry mass (only if all usual moist species are prognostic)
!!!!!
IF(YGFL%YQ%LADV .AND. YGFL%YL%LADV .AND.YGFL%YI%LADV .AND.YGFL%YR%LADV .AND.YGFL%YS%LADV) THEN
  IGFLADV=1
  ALLOCATE(ZWORK5(YDGEOMETRY%YRDIM%NPROMA,2*IGFLADV,YDGEOMETRY%YRDIM%NGPBLKS))
  ALLOCATE(ZGFLNORMS(3,2*IGFLADV))
  ALLOCATE(ZGFLNORMS_DP(3,2*IGFLADV))

IST=1
DO JJ=1,IGFLADV
!$OMP PARALLEL DO SCHEDULE(STATIC) &
!$OMP& PRIVATE(JKGLO,IEND,IBL,JLEV,JROF) &
!$OMP& PRIVATE(ZPRE0,ZPRE1,ZWORK3T0,ZWORK3T1,ZWORK2T0,ZWORK2T1)
  DO JKGLO=1,YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIM%NPROMA
    IEND=MIN(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRGEM%NGPTOT-JKGLO+1)
    IBL=(JKGLO-1)/YDGEOMETRY%YRDIM%NPROMA+1
    ZPRE0(IST:IEND,0)=ZPRES0(IST:IEND,0,IBL)
    ZPRE1(IST:IEND,0)=ZPRES1(IST:IEND,0,IBL)
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=IST,IEND
! dry mass specific ratio
        ZWORK3T0(JROF,JLEV)=1._JPRB-PGFL(JROF,JLEV,YGFL%YQ%MP9_PH,IBL) &
 &                                 -PGFL(JROF,JLEV,YGFL%YL%MP9_PH,IBL)-PGFL(JROF,JLEV,YGFL%YI%MP9_PH,IBL) &
 &                                 -PGFL(JROF,JLEV,YGFL%YS%MP9_PH,IBL)-PGFL(JROF,JLEV,YGFL%YR%MP9_PH,IBL)
        ZWORK3T1(JROF,JLEV)=1._JPRB-PGFLT1(JROF,JLEV,YGFL%YQ%MP1,IBL) &
 &                                 -PGFLT1(JROF,JLEV,YGFL%YL%MP1,IBL)-PGFLT1(JROF,JLEV,YGFL%YI%MP1,IBL) &
 &                                 -PGFLT1(JROF,JLEV,YGFL%YS%MP1,IBL)-PGFLT1(JROF,JLEV,YGFL%YR%MP1,IBL)
        ZPRE0(JROF,JLEV) = ZPRES0(JROF,JLEV,IBL) 
        ZPRE1(JROF,JLEV) = ZPRES1(JROF,JLEV,IBL)
        IF (ZPTROP(JROF,IBL) >= ZPRE0(JROF,JLEV)) ZWORK3T0(JROF,JLEV)=0.0_JPRB 
        IF (ZPTROP(JROF,IBL) >= ZPRE1(JROF,JLEV)) ZWORK3T1(JROF,JLEV)=0.0_JPRB 
      ENDDO
    ENDDO
    IF (YGFL%NOPTVFE==1) THEN
      CALL GPPWCVFE(YDGEOMETRY,YDGEOMETRY%YRDIM%NPROMA,IST,IEND,YDGEOMETRY%YRDIMV%NFLEVG,ZWORK2T0,ZWORK3T0,ZPRE0)
      CALL GPPWCVFE(YDGEOMETRY,YDGEOMETRY%YRDIM%NPROMA,IST,IEND,YDGEOMETRY%YRDIMV%NFLEVG,ZWORK2T1,ZWORK3T1,ZPRE1)
    ELSE
      CALL GPPWC(YDGEOMETRY%YRDIM%NPROMA,IST,IEND,YDGEOMETRY%YRDIMV%NFLEVG,ZWORK2T0,ZWORK3T0,ZPRE0)
      CALL GPPWC(YDGEOMETRY%YRDIM%NPROMA,IST,IEND,YDGEOMETRY%YRDIMV%NFLEVG,ZWORK2T1,ZWORK3T1,ZPRE1)
    ENDIF
    DO JROF=IST,IEND
      ZWORK5(JROF,2*JJ-1,IBL)=ZWORK2T0(JROF,YDGEOMETRY%YRDIMV%NFLEVG)
      ZWORK5(JROF,2*JJ,IBL)=ZWORK2T1(JROF,YDGEOMETRY%YRDIMV%NFLEVG)
    ENDDO
  ENDDO
!$OMP END PARALLEL DO
ENDDO

  IF (NPROC==1.OR.MYPROC==1) THEN
  WRITE(NULOUT,*)
  WRITE(NULOUT,*) '-----------  ' , CLDOMAIN, 'MASS BUDGETS before vs after SL ', CLT, ' -----------'
  ENDIF
  CALL GPNORM1(YDGEOMETRY,ZWORK5,2*IGFLADV,.FALSE.,PNORMS=ZGFLNORMS,PNORMS_DP=ZGFLNORMS_DP)
  IF (NPROC==1.OR.MYPROC==1) THEN
    WRITE(NULOUT,*) '        DRY AIR     mean MASS(kgr/m**2)   total MASS(kgr)    mean PRESS(Pa)    '
    WRITE(NULOUT,*) '-------------------------------------------------------------------------------'
    DO JJ=1,IGFLADV
      WRITE(NULOUT,'(A20,2X,F20.12,2X,E20.15,2X,F20.12)') "DRY AIR", &
        & ZGFLNORMS_DP(1,2*JJ-1),ZAREA*ZGFLNORMS_DP(1,2*JJ-1),RG*ZGFLNORMS_DP(1,2*JJ-1)
      WRITE(NULOUT,'(22X,F20.12,2X,E20.15,2X,F20.12)') ZGFLNORMS_DP(1,2*JJ),&
        & ZAREA*ZGFLNORMS_DP(1,2*JJ),RG*ZGFLNORMS_DP(1,2*JJ)
    ENDDO
    WRITE(NULOUT,*) '-------------------------------------------------------------------------------'
    WRITE(NULOUT,*)
  ENDIF
  DEALLOCATE(ZWORK5)
  DEALLOCATE(ZGFLNORMS)
  DEALLOCATE(ZGFLNORMS_DP)

! Test moist species active
ENDIF
ENDIF


IF (LHOOK) CALL DR_HOOK('GMASSDIAG',1,ZHOOK_HANDLE)

END SUBROUTINE GMASSDIAG
