! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! Module: STOCHASTIC_ROUNDING_MOD
! Purpose: Modular stochastic rounding and PRNG utilities for Single Precision (SP)
!          unbiased float32 truncation in atmospheric tracer mass fixers.

MODULE STOCHASTIC_ROUNDING_MOD

USE PARKIND1, ONLY : JPIM, JPIB, JPRB, JPRD

IMPLICIT NONE

PRIVATE
PUBLIC :: LSTOCHASTIC_ROUNDING, STOCH_ROUND_INIT, STOCHASTIC_ROUND_VAL, XORSHIFT64_UNIFORM

LOGICAL, SAVE :: LSTOCHASTIC_ROUNDING = .TRUE.
LOGICAL, SAVE :: LL_INIT_SR = .FALSE.

CONTAINS

SUBROUTINE STOCH_ROUND_INIT(KULOUT, KMYPROC, LDSTOCH_ROUNDING)
  INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KULOUT
  INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KMYPROC
  LOGICAL, INTENT(IN), OPTIONAL :: LDSTOCH_ROUNDING
  CHARACTER(LEN=32) :: CLENV_SR
  INTEGER(KIND=JPIM) :: IULOUT, IMYPROC

  IF (LL_INIT_SR) RETURN
  LL_INIT_SR = .TRUE.

  IULOUT = 6_JPIM
  IF (PRESENT(KULOUT)) IULOUT = KULOUT

  IMYPROC = 1_JPIM
  IF (PRESENT(KMYPROC)) IMYPROC = KMYPROC

  ! Default from NAMGFL if provided, otherwise default to SP=.TRUE. / DP=.FALSE.
  IF (PRESENT(LDSTOCH_ROUNDING)) THEN
    LSTOCHASTIC_ROUNDING = LDSTOCH_ROUNDING
  ELSE
    IF (KIND(1.0_JPRB) == KIND(1.0_JPRD)) THEN
      LSTOCHASTIC_ROUNDING = .FALSE.
    ELSE
      LSTOCHASTIC_ROUNDING = .TRUE.
    ENDIF
  ENDIF

  ! Environment variable override: OIFS_ROUNDING_MODE takes precedence if explicitly set
  CALL GET_ENVIRONMENT_VARIABLE('OIFS_ROUNDING_MODE', CLENV_SR)
  IF (TRIM(CLENV_SR) == 'RN' .OR. TRIM(CLENV_SR) == 'rn' .OR. TRIM(CLENV_SR) == 'IEEE') THEN
    LSTOCHASTIC_ROUNDING = .FALSE.
  ELSEIF (TRIM(CLENV_SR) == 'SR' .OR. TRIM(CLENV_SR) == 'sr') THEN
    LSTOCHASTIC_ROUNDING = .TRUE.
  ENDIF

  IF (IMYPROC == 1) THEN
    IF (LSTOCHASTIC_ROUNDING) THEN
      WRITE(IULOUT,'(A)') 'STOCHASTIC_ROUNDING: Mode = Stochastic Rounding (SR)'
    ELSE
      WRITE(IULOUT,'(A)') 'STOCHASTIC_ROUNDING: Mode = Deterministic IEEE 754 (RN)'
    ENDIF
  ENDIF
END SUBROUTINE STOCH_ROUND_INIT

PURE ELEMENTAL FUNCTION XORSHIFT64_UNIFORM(KSEED) RESULT(PRAND)
  INTEGER(KIND=JPIB), INTENT(IN) :: KSEED
  REAL(KIND=JPRD) :: PRAND
  INTEGER(KIND=JPIB) :: ISEED
  INTEGER(KIND=JPIM) :: JR

  ! Mask to 63-bit positive signed integer
  ISEED = IAND(KSEED, 9223372036854775807_JPIB)
  IF (ISEED == 0_JPIB) ISEED = 88172645463325252_JPIB

  ! 3 rounds of bitwise xorshift diffusion for uniform spatial distribution
  DO JR = 1, 3
    ISEED = IAND(IEOR(ISEED, ISHFT(ISEED, 13)), 9223372036854775807_JPIB)
    ISEED = IEOR(ISEED, ISHFT(ISEED, -7))
    ISEED = IAND(IEOR(ISEED, ISHFT(ISEED, 17)), 9223372036854775807_JPIB)
  ENDDO

  ! Convert 63 positive pseudo-random bits to [0, 1) in double precision
  PRAND = REAL(ISEED, KIND=JPRD) * 1.0842021724855044E-19_JPRD
END FUNCTION XORSHIFT64_UNIFORM

PURE FUNCTION STOCHASTIC_ROUND_VAL(PVAL_DP, KSEED) RESULT(PRES_SP)
  REAL(KIND=JPRD), INTENT(IN) :: PVAL_DP
  INTEGER(KIND=JPIB), INTENT(IN) :: KSEED
  REAL(KIND=JPRB) :: PRES_SP
  REAL(KIND=JPRB) :: ZVAL_SP, ZNEXT_SP
  REAL(KIND=JPRD) :: ZDIFF_DP, ZSTEP_DP, ZRAND

  ZVAL_SP = REAL(PVAL_DP, KIND=JPRB)
  ZDIFF_DP = PVAL_DP - DBLE(ZVAL_SP)

  IF (ZDIFF_DP /= 0.0_JPRD) THEN
    ZNEXT_SP = NEAREST(ZVAL_SP, SIGN(1.0_JPRB, REAL(ZDIFF_DP, KIND=JPRD)))
    ZSTEP_DP = ABS(DBLE(ZNEXT_SP) - DBLE(ZVAL_SP))
    ZRAND = XORSHIFT64_UNIFORM(KSEED)
    IF (ZRAND * ZSTEP_DP < ABS(ZDIFF_DP)) THEN
      PRES_SP = ZNEXT_SP
    ELSE
      PRES_SP = ZVAL_SP
    ENDIF
  ELSE
    PRES_SP = ZVAL_SP
  ENDIF
END FUNCTION STOCHASTIC_ROUND_VAL

END MODULE STOCHASTIC_ROUNDING_MOD
